# Generated by Django 5.0.1 on 2024-02-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(default='https://example.com/apply'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='https://example.com/apply', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_website',
            field=models.URLField(default='https://example.com/apply'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_details',
            field=models.TextField(default='Default job details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_role',
            field=models.CharField(default='Default job details', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='work_location',
            field=models.CharField(default='Default job details', max_length=100),
            preserve_default=False,
        ),
    ]
