# Generated by Django 5.0.1 on 2024-02-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_job_apply_link_job_company_name_job_company_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Default Company Name', max_length=100),
        ),
    ]
