# Generated by Django 5.0.1 on 2024-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0004_alter_job_description_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='batch',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='job',
            name='package',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.URLField(default='none'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_website',
            field=models.URLField(default='none'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_details',
            field=models.TextField(default='none'),
        ),
    ]
