# Generated by Django 5.0.1 on 2024-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0005_job_batch_job_experience_job_job_type_job_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='about_company',
            field=models.TextField(default='none'),
        ),
    ]
